-- MySQL Script generated by MySQL Workbench
-- Thu Nov 12 13:04:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`personas` (
  `IdPersona` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`IdPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuarios` (
  `IdUsuario` INT NOT NULL,
  `Usuario` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `IdPersona` INT NULL,
  PRIMARY KEY (`IdUsuario`),
  INDEX `IdPersona_idx` (`IdPersona` ASC) VISIBLE,
  CONSTRAINT `IdPersona`
    FOREIGN KEY (`IdPersona`)
    REFERENCES `biblioteca`.`personas` (`IdPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`roles` (
  `IdRoles` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`IdRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario_rol` (
  `IdUsuarioRol` INT NOT NULL,
  `IdRol` INT NULL,
  `IdUsuario` INT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`IdUsuarioRol`),
  INDEX `fk_usuario_rol_idx` (`IdUsuario` ASC) VISIBLE,
  INDEX `fk_rol_usuario_idx` (`IdRol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `biblioteca`.`usuarios` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_usuario`
    FOREIGN KEY (`IdRol`)
    REFERENCES `biblioteca`.`roles` (`IdRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`permisos` (
  `IdPermisos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `slug` VARCHAR(50) NULL,
  PRIMARY KEY (`IdPermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`permiso_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`permiso_rol` (
  `IdPermisoRol` INT NOT NULL,
  `IdPermiso` INT NULL,
  `IdRol` INT NULL,
  PRIMARY KEY (`IdPermisoRol`),
  INDEX `fk_permiso_rol_idx` (`IdPermiso` ASC) VISIBLE,
  INDEX `fk_rol_permiso_idx` (`IdRol` ASC) VISIBLE,
  CONSTRAINT `fk_permiso_rol`
    FOREIGN KEY (`IdPermiso`)
    REFERENCES `biblioteca`.`permisos` (`IdPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_permiso`
    FOREIGN KEY (`IdRol`)
    REFERENCES `biblioteca`.`roles` (`IdRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro` (
  `IdLibro` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `isbn` VARCHAR(45) NULL,
  `Autor` VARCHAR(45) NULL,
  `Cantidad` TINYINT NULL,
  `Editorial` VARCHAR(45) NULL,
  `Foto` VARCHAR(100) NULL,
  PRIMARY KEY (`IdLibro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`libro_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`libro_prestamo` (
  `IdLibroPrestamo` INT NOT NULL,
  `IdUsuario` INT NULL,
  `IdLibro` INT NULL,
  `FechaPrestamo` DATE NULL,
  `FechaDevolucion` DATE NULL,
  `Estado` TINYINT NULL,
  PRIMARY KEY (`IdLibroPrestamo`),
  INDEX `fk_prestamo_usuario_idx` (`IdUsuario` ASC) VISIBLE,
  INDEX `fk_prestamo_libro_idx` (`IdLibro` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_usuario`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `biblioteca`.`usuarios` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_libro`
    FOREIGN KEY (`IdLibro`)
    REFERENCES `biblioteca`.`libro` (`IdLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
